# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Set the documentation variant based on READTHEDOCS_VERSION_NAME or RTD_VARIANT env variable
      - |
        if [ "$RTD_VARIANT" = "matlab" ]; then
          echo "Building MATLAB documentation"
          echo "CONF_DIR=source/conf_matlab" >> $READTHEDOCS_ENV
        else
          echo "Building Python documentation"
          echo "CONF_DIR=source/conf_python" >> $READTHEDOCS_ENV
        fi

sphinx:
  configuration: ${CONF_DIR}/conf.py
  builder: html

python:
  install:
    - requirements: requirements.txt
